import * as dotenv from 'dotenv'

// Load environment variables
dotenv.config({ path: '.env.local' })

console.log('🛡️  Migration 010: Enable Super Admin')
console.log('=====================================')
console.log('')
console.log('This migration will:')
console.log('1. Add is_super_admin column to users table')
console.log('2. Make levan@sarke.ge a super admin')
console.log('3. Add tenant management fields (is_active, notes)')
console.log('4. Add app limits support for future use')
console.log('')
console.log('✅ What you get:')
console.log('- /super-admin dashboard (protected)')
console.log('- View all tenants and stats')
console.log('- Toggle apps on/off per tenant')
console.log('- Suspend/activate tenants')
console.log('')
console.log('To apply this migration:')
console.log('----------------------------------------')
console.log('1. Go to Supabase SQL Editor:')
console.log(`   https://supabase.com/dashboard/project/${process.env.NEXT_PUBLIC_SUPABASE_URL?.split('.')[0].replace('https://', '')}/sql/new`)
console.log('')
console.log('2. Copy ALL content from:')
console.log('   supabase/migrations/010_add_super_admin.sql')
console.log('')
console.log('3. Paste and click "Run"')
console.log('')
console.log('4. After applying:')
console.log('   - Login as levan@sarke.ge')
console.log('   - You will see a red "Super Admin" button')
console.log('   - Click it to access the super admin panel')
console.log('')
console.log('🔒 Security: Only users with is_super_admin=true can access /super-admin')