import * as dotenv from 'dotenv'

// Load environment variables
dotenv.config({ path: '.env.local' })

console.log('🏢 Migration 011: Setup Komunate as Regular Tenant')
console.log('================================================')
console.log('')
console.log('This migration transforms komunate.com from a "special platform domain"')
console.log('to a regular tenant with a verified custom domain.')
console.log('')
console.log('✨ What will happen:')
console.log('1. Add levan@sarke.ge as owner of komunate tenant')
console.log('2. Add komunate.com as verified custom domain')
console.log('3. Enable all apps for komunate tenant')
console.log('4. Remove special platform logic from code')
console.log('')
console.log('📋 After this migration:')
console.log('• komunate.komunate.com → Tenant subdomain (backup access)')
console.log('• komunate.com → Primary custom domain')
console.log('• Login redirects to komunate.com (not subdomain)')
console.log('• Super admin still works (user property)')
console.log('• Page Builder edits affect komunate.com')
console.log('')
console.log('🚀 How to apply:')
console.log('----------------------------------------')
console.log('1. Go to Supabase SQL Editor:')
console.log(`   https://supabase.com/dashboard/project/${process.env.NEXT_PUBLIC_SUPABASE_URL?.split('.')[0].replace('https://', '')}/sql/new`)
console.log('')
console.log('2. Copy ALL content from:')
console.log('   supabase/migrations/011_setup_komunate_tenant.sql')
console.log('')
console.log('3. Paste and click "Run"')
console.log('')
console.log('4. After running, clear your browser cookies')
console.log('')
console.log('5. Login to komunate.com with levan@sarke.ge')
console.log('')
console.log('💡 Important Notes:')
console.log('• This is a one-way migration (komunate.com becomes a tenant)')
console.log('• You may need to restart the app after applying')
console.log('• The homepage will now serve from komunate tenant blob storage')
console.log('')
console.log('🎉 This demonstrates the platform eating its own dog food!')